#Server
server:
  port: 8080

# JPA
spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:people

  # Database
  h2:
    console:
      enabled: true

# Actuator metrics
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
